import Head from "next/head";
import fsPromises from "fs/promises";
import path from "path";
import GridLayout from "react-grid-layout";

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), "elementos.json");
  const jsonData = await fsPromises.readFile(filePath);
  const objectData = JSON.parse(jsonData);
  return {
    props: objectData,
  };
}

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Tabela Peridica dos Elementos - IFPR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <GridLayout className="layout" cols={12} rowHeight={30} width={1200}>
          <div key="a" data-grid={{ x: 0, y: 0, w: 1, h: 2, static: true }}>
            a
          </div>
          <div key="b" data-grid={{ x: 1, y: 0, w: 3, h: 2, minW: 2, maxW: 4 }}>
            b
          </div>
          <div key="c" data-grid={{ x: 4, y: 0, w: 1, h: 2 }}>
            c
          </div>
        </GridLayout>
        <h1>TABELA PERIÓDICA - ELEMENTOS</h1>
        <div className="table_container">
          <table cellSpacing="0" cellPadding="0">
            <tbody>
              <tr>
                <td className="ametais" style={{ backgroundColor: "#96cd30" }}>
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td
                  className="gases-nobres"
                  style={{ backgroundColor: "#3d9ee3" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
              </tr>
              <tr>
                <td
                  className="metais-alcalinos"
                  style={{ backgroundColor: "#EADA00" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-alcalinos"
                  style={{ backgroundColor: "#EADA00" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td
                  className="semimetais"
                  style={{ backgroundColor: "#44a69c" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td className="ametais" style={{ backgroundColor: "#96cd30" }}>
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td className="ametais" style={{ backgroundColor: "#96cd30" }}>
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td className="ametais" style={{ backgroundColor: "#96cd30" }}>
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="halogenios"
                  style={{ backgroundColor: "#70cbeb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="gases-nobres"
                  style={{ backgroundColor: "#3d9ee3" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
              </tr>
              <tr>
                <td
                  className="metais-alcalinos"
                  style={{ backgroundColor: "#EADA00" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-alcalinos"
                  style={{ backgroundColor: "#EADA00" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#44a69c" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="semimetais"
                  style={{ backgroundColor: "#44a69c" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td className="ametais" style={{ backgroundColor: "#96cd30" }}>
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td className="ametais" style={{ backgroundColor: "#96cd30" }}>
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="halogenios"
                  style={{ backgroundColor: "#70cbeb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="gases-nobres"
                  style={{ backgroundColor: "#3d9ee3" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
              </tr>
              <tr>
                <td
                  className="metais-alcalinos"
                  style={{ backgroundColor: "#EADA00" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-alcalinos"
                  style={{ backgroundColor: "#EADA00" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#91bdcb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="semimetais"
                  style={{ backgroundColor: "#44a69c" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="semimetais"
                  style={{ backgroundColor: "#44a69c" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td className="ametais" style={{ backgroundColor: "#96cd30" }}>
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="halogenios"
                  style={{ backgroundColor: "#70cbeb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="gases-nobres"
                  style={{ backgroundColor: "#3d9ee3" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
              </tr>
              <tr>
                <td
                  className="metais-alcalinos"
                  style={{ backgroundColor: "#EADA00" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-alcalinos"
                  style={{ backgroundColor: "#EADA00" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#91bdcb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#91bdcb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="semimetais"
                  style={{ backgroundColor: "#44a69c" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="semimetais"
                  style={{ backgroundColor: "#44a69c" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="halogenios"
                  style={{ backgroundColor: "#70cbeb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="gases-nobres"
                  style={{ backgroundColor: "#3d9ee3" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
              </tr>
              <tr>
                <td
                  className="metais-alcalinos"
                  style={{ backgroundColor: "#EADA00" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-alcalinos"
                  style={{ backgroundColor: "#EADA00" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="lantanideos"
                  style={{ backgroundColor: "#90e3e9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#91bdcb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#91bdcb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#91bdcb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="semimetais"
                  style={{ backgroundColor: "#44a69c" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="halogenios"
                  style={{ backgroundColor: "#70cbeb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="gases-nobres"
                  style={{ backgroundColor: "#3d9ee3" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
              </tr>
              <tr>
                <td
                  className="metais-alcalinos"
                  style={{ backgroundColor: "#EADA00" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-alcalinos"
                  style={{ backgroundColor: "#EADA00" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="actinidios"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#f78585" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#e77878" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#91bdcb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#91bdcb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#91bdcb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#91bdcb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="halogenios"
                  style={{ backgroundColor: "#70cbeb" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="gases-nobres"
                  style={{ backgroundColor: "#4aaaf0" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
              </tr>
              <tr>
                <td>
                  <span>&nbsp;</span>
                </td>
              </tr>
              <tr>
                <td>
                  <span>&nbsp;</span>
                </td>
              </tr>
              <tr className="elemento-espaço">
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="halogenios"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="gases-nobres"
                  style={{ backgroundColor: "#90E3E9" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
              </tr>
              <tr>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td>
                  <div className="elemento-periodo">&nbsp;</div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="metais-transiçao"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="outros-metais"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td className="outros-" style={{ backgroundColor: "#dcadd6" }}>
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="actinidios"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
                <td
                  className="actinidios"
                  style={{ backgroundColor: "#dcadd6" }}
                >
                  <div className="elemento-periodo">
                    <span className="numero_elemento">1</span>
                    <span className="nome_elemento">
                      <b>H</b>
                    </span>
                    <span className="m_atomica">1</span>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </main>
    </>
  );
}
